<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Logout</name>
   <tag></tag>
   <elementGuidId>07f16b84-9a30-47c4-8200-91a9960a5b1e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>span.ng-tns-c292-0</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//app-root[@id='angular-root']/body/div/app-main-layout/app-header/header/div/div/div[2]/a/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>25121f71-247d-4d07-a1f1-ebcbf22ae977</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ng-tns-c292-0</value>
      <webElementGuid>7fd8a35d-2067-4e76-b2bb-87d650c4ddbf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Logout</value>
      <webElementGuid>db874fe9-6656-423d-8e5e-08b3e268829f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;angular-root&quot;)/body[1]/div[1]/app-main-layout[@class=&quot;ng-star-inserted&quot;]/app-header[@class=&quot;ng-tns-c292-0&quot;]/header[@class=&quot;main-header ng-tns-c292-0&quot;]/div[@class=&quot;container-fluid mobile-menu ng-tns-c292-0&quot;]/div[@class=&quot;row p-0 top-head ng-tns-c292-0&quot;]/div[@class=&quot;col-8 head-top-right ng-tns-c292-0&quot;]/a[@class=&quot;default-icon logout-link ng-tns-c292-0&quot;]/span[@class=&quot;ng-tns-c292-0&quot;]</value>
      <webElementGuid>3b1922c2-b31e-4f21-abc1-842ebd448e15</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//app-root[@id='angular-root']/body/div/app-main-layout/app-header/header/div/div/div[2]/a/span</value>
      <webElementGuid>6615ebbd-80e7-4542-adfe-11267af65a51</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='See all notifications'])[1]/following::span[1]</value>
      <webElementGuid>af284d46-5cd5-461c-9dc0-509fcbe44c50</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='There are no new notifications.'])[1]/following::span[1]</value>
      <webElementGuid>6e8b846b-3ece-46cc-adbe-fb8cf5da93d9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='(current)'])[1]/preceding::span[1]</value>
      <webElementGuid>55548437-ec32-4a2f-bee2-0ec483edc86a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Logout']/parent::*</value>
      <webElementGuid>4b7fe8ed-48f2-4849-be87-6229b6ad47b4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/a/span</value>
      <webElementGuid>3a6431ed-3c69-4bb4-973f-0ddcab181a32</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Logout' or . = 'Logout')]</value>
      <webElementGuid>f84acdf3-f051-4125-8184-5acf988db191</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
